version: '3.5'

services:
  package:
    build:
      args:
        - PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT:-8000M}
        - PHP_MAX_EXECUTION_TIME=${PHP_MAX_EXECUTION_TIME:-7200}
        - PHP_MAX_UPLOAD=${PHP_MAX_UPLOAD:-50M}
        - PHP_MAX_FILE_UPLOAD=${PHP_MAX_FILE_UPLOAD:-200}
        - PHP_MAX_POST=${PHP_MAX_POST:-100M}
        - OPCACHE_MEMORY_CONSUMPTION=${OPCACHE_MEMORY_CONSUMPTION:-512}
        - OPCACHE_INTERNED_STRINGS_BUFFER=${OPCACHE_INTERNED_STRINGS_BUFFER:-8}
        - OPCACHE_MAX_ACCELERATED_FILES=${OPCACHE_MAX_ACCELERATED_FILES:-4000}
        - OPCACHE_REVALIDATE_FREQ=${OPCACHE_REVALIDATE_FREQ:-2}
        - OPCACHE_FAST_SHUTDOWN=${OPCACHE_FAST_SHUTDOWN:-2}
        - OPCACHE_ENABLE_CLI=${OPCACHE_ENABLE_CLI:-1}
    image: talenly:php-workspace
    volumes:
      - ./:/var/www/api:delegated
